# Define the directory and dataset path to generate and save

In [166]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [167]:
directory = "/content/drive/MyDrive/eightfold" # Name the directory to save generated dataset
file_name = "generated_data.csv"
dataset_path = f"{directory}/{file_name}"

In [168]:
species = ['Aquari', 'Zorblax', 'Florian', 'Faerix', 'Nexoon', 'Mythron',
       'Emotivor', 'Sentire', 'Quixnar', 'Cybex']

# Creating the dataset
Run to generate dataset, else move to the next section

In [169]:
# Defining the maximum limit of each dataframe column
max_limit = {
    "rank": 5,
    "wars_won": 50,
    "wars_lost": 50,
    "medalsAwarded": 20,
    "no_Of_punishment": 20,
    "yearsSpentInRank": 30,
    "money": 100000,
    "no_of_conversations_with_phygerian": 100,
    "no_of_species_of_this_kind": 10,
    "no_of_converations_w_others": 100,
    "no_of_arguments_w_others": 20
}

In [170]:
feature_list = ["species"] + list(max_limit.keys())

In [171]:
import pandas as pd
import random

# Create an empty list to store the data
data = []

total_wars = 110

# Generating 1000 rows of random data with anomalies
for _ in range(1000):
  row = []
  row.append(random.choice(species))  # species
  row.append(random.randint(1, max_limit["rank"]))  # rank
  row.append(random.randint(0, max_limit["wars_won"]))  # wars_won
  row.append(random.randint(0, max_limit["wars_lost"]))  # wars_lost
  row.append(random.randint(0, max_limit["medalsAwarded"]) + int((random.random() > 0.9) * random.random() * max_limit["medalsAwarded"]))  # medalsAwarded
  row.append(random.randint(0, max_limit["no_Of_punishment"]) + int((random.random() > 0.8) * random.random() * max_limit["no_Of_punishment"]))  # no_Of_punishment
  row.append(random.randint(1, max_limit["yearsSpentInRank"]) + int((random.random() > 0.7) * random.random() * max_limit["yearsSpentInRank"]))  # yearsSpentInRank
  row.append(random.randint(0, max_limit["money"]) + int((random.random() > 0.9) * random.random() * max_limit["money"]))  # money
  row.append(random.randint(0, max_limit["no_of_conversations_with_phygerian"]))  # no_of_conversations_with_phygerian
  row.append(0)  # no_of_species_of_this_kind -> to be calculated later from "species" column
  row.append(random.randint(0, max_limit["no_of_converations_w_others"]))  # no_of_converations_w_others
  row.append(random.randint(0, max_limit["no_of_arguments_w_others"]) + int((random.random() > 0.8) * random.random() * max_limit["no_of_arguments_w_others"]))  # no_of_arguments_w_others
  data.append(row)

df = pd.DataFrame(data, columns=feature_list)

In [172]:
# Finding the additional columns
for i, row in df.iterrows():
  df.at[i, "no_of_species_of_this_kind"] = df["species"].value_counts()[df.at[i, "species"]]

df["wars_participated_percentage"] = (df["wars_won"] + df["wars_lost"]) / total_wars * 100

In [173]:
df.to_csv(dataset_path, index=False)

# Solution Pipeline

In [180]:
"""Read dataset"""
df = pd.read_csv(dataset_path)

In [181]:
"""Class Xernian with defined properties"""
class Xernian:
    def __init__(self):
        self.rank = 0
        self.wars_won = 0.0
        self.wars_lost = 0.0
        self.medalsAwarded = 0.0
        self.yearsSpentInRank = 0.0
        self.money = 0.0
        self.no_Of_punishment = 0.0
        self.no_of_conversations_with_pygerian = 0.0
        self.no_of_species_of_this_kind = 0.0
        self.no_of_conversations_w_others = 0.0
        self.no_of_arguments_w_others = 0.0

"""Function to generate the betrayal chance of each soldier"""
def betrayal_function(soldiers, weights, no_of_wars):
    N = len(soldiers)
    betrayalChance = [0] * N
    total_medals = total_money = total_punishment = 0.0
    total_convs_pyge = 0.0
    max_years = 0.0
    total_conversations = total_arguments = total_xerninan_in_rank = 0.0

    for soldier in soldiers:
        total_medals += soldier.medalsAwarded
        total_money += soldier.money
        total_punishment += soldier.no_Of_punishment
        total_convs_pyge += soldier.no_of_conversations_with_pygerian
        max_years = max(max_years, soldier.yearsSpentInRank)
        total_conversations += soldier.no_of_conversations_w_others
        total_arguments += soldier.no_of_arguments_w_others
        total_xerninan_in_rank += soldier.no_of_species_of_this_kind

    # Normalise each column before fiding final cost
    for i in range(N):
        soldier = soldiers[i]
        war_participated_percentage = (soldier.wars_lost + soldier.wars_won) * 10.0 / no_of_wars if no_of_wars > 0 else 0
        war_won_percentage = soldier.wars_won * 10.0 / (soldier.wars_lost + soldier.wars_won) if (soldier.wars_lost + soldier.wars_won > 0) else 0
        war_lost_percentage = soldier.wars_lost * 10.0 / (soldier.wars_lost + soldier.wars_won) if (soldier.wars_lost + soldier.wars_won > 0) else 0
        medal_winning_percentage = soldier.medalsAwarded * 10.0 / total_medals if (total_medals > 0) else 0
        money_percentage = soldier.money * 10.0 / total_money if (total_money > 0) else 0
        punishment_percentage = soldier.no_Of_punishment * 10.0 / total_punishment if (total_punishment > 0) else 0
        convs_pyge_percentage = soldier.no_of_conversations_with_pygerian * 10.0 / total_convs_pyge if (total_convs_pyge > 0) else 0
        years_spent_normalised = soldier.yearsSpentInRank * 10.0 / max_years if (max_years > 0) else 0

        species_similar_normalized = soldier.no_of_species_of_this_kind / total_xerninan_in_rank if (total_xerninan_in_rank > 0) else 0
        conversations_normalized = soldier.no_of_conversations_w_others / total_conversations if (total_conversations > 0) else 0
        arguments_normalized = soldier.no_of_arguments_w_others / total_arguments if (total_arguments > 0) else 0

        # Cost Function
        betrayalChance[i] = (weights[0] * war_participated_percentage +
                             weights[1] * war_won_percentage -
                             weights[2] * war_lost_percentage +
                             weights[3] * medal_winning_percentage -
                             weights[4] * money_percentage -
                             weights[5] * punishment_percentage -
                             weights[6] * convs_pyge_percentage -
                             weights[7] * years_spent_normalised +
                             weights[8] * species_similar_normalized +
                             weights[9] * conversations_normalized -
                             weights[10] * arguments_normalized)

    return betrayalChance

"""Generates weights of importance to each feature using Analytical Hierarchy Process"""
def ahp_weights(matrix):
    N = len(matrix)
    colSum = [0.0] * N
    weights = [0.0] * N

    # Step 1: Sum each column of the matrix
    for i in range(N):
        for j in range(N):
            colSum[i] += matrix[j][i]

    # Step 2: Normalize the matrix
    normalizedMatrix = [[0.0] * N for _ in range(N)]
    for i in range(N):
        for j in range(N):
            normalizedMatrix[i][j] = matrix[i][j] / colSum[j]

    # Step 3: Calculate the average weight of each row
    for i in range(N):
        rowSum = sum(normalizedMatrix[i])
        weights[i] = rowSum / N

    return weights

In [183]:
# Pairwise comparison matrix based on qualitative comparison between each feature
pairwise_comparison_matrix = [
        [1, 5, 5, 7, 1, 9, 9, 9, 9, 1, 1],    # war_participated_percentage
        [1, 1, 1, 3, 1, 5, 5, 5, 5, 1, 1],    # war_won_percentage
        [1, 1, 1, 3, 1, 5, 5, 5, 5, 1, 1],    # war_lost_percentage
        [1, 1, 1, 1, 3, 3, 3, 3, 3, 1, 1],  # medal_winning_percentage
        [1, 1, 1, 1, 1, 9, 9, 9, 9, 9, 9],   # money_percentage
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],   # punishment_percentage
        [1, 1, 1, 1, 1, 1, 1, 7, 7, 7, 7], # convs_pyge_percentage
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], # years_spent_normalized
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], # species_similar_normalized
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], # conversations_normalized
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]  # arguments
    ]

for i in range(len(pairwise_comparison_matrix)):
    for j in range(len(pairwise_comparison_matrix[i])):
        pairwise_comparison_matrix[j][i] = 1 / pairwise_comparison_matrix[i][j]

#Generate weights using AHP
weights = ahp_weights(pairwise_comparison_matrix)

In [184]:
soldiers = []
for i, row in df.iterrows():
    soldier = Xernian()
    soldier.rank = row["rank"]
    soldier.wars_won = row["wars_won"]
    soldier.wars_lost = row["wars_lost"]
    soldier.medalsAwarded = row["medalsAwarded"]
    soldier.yearsSpentInRank = row["yearsSpentInRank"]
    soldier.money = row["money"]
    soldier.no_Of_punishment = row["no_Of_punishment"]
    soldier.no_of_conversations_with_pygerian = row["no_of_conversations_with_phygerian"]
    soldier.no_of_species_of_this_kind = row["no_of_species_of_this_kind"]
    soldier.no_of_conversations_w_others = row["no_of_converations_w_others"]
    soldier.no_of_arguments_w_others = row["no_of_arguments_w_others"]
    soldiers.append(soldier)

In [185]:
from collections import defaultdict
rank_map = defaultdict(list)

for soldier in soldiers:
    rank_map[soldier.rank].append(soldier)

for rank, soldiers in rank_map.items():
    betrayal_chances = betrayal_function(soldiers, weights, total_wars)

    min_val = float('inf')
    ans = -1
    for i, chance in enumerate(betrayal_chances):
        if chance < min_val:
            min_val = chance
            ans = i
    print(f"One with the highest betrayal Chance is Xernian of Rank #{rank}: {ans + 1}")

One with the highest betrayal Chance is Xernian of Rank #4: 110
One with the highest betrayal Chance is Xernian of Rank #1: 171
One with the highest betrayal Chance is Xernian of Rank #5: 20
One with the highest betrayal Chance is Xernian of Rank #3: 68
One with the highest betrayal Chance is Xernian of Rank #2: 72

In [186]:
df

,species,rank,wars_won,wars_lost,medalsAwarded,no_Of_punishment,yearsSpentInRank,money,no_of_conversations_with_phygerian,no_of_species_of_this_kind,no_of_converations_w_others,no_of_arguments_w_others,wars_participated_percentage
0,Quixnar,4,4,48,4,17,18,39823,37,96,1,12,47.272727
1,Aquari,4,5,48,4,8,16,75507,46,101,37,12,48.181818
2,Zorblax,1,37,14,11,2,25,33053,13,111,46,17,46.363636
3,Nexoon,5,40,44,4,9,37,38024,74,94,84,19,76.363636
4,Zorblax,5,26,22,4,15,21,76813,41,111,51,19,43.636364
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Nexoon,3,35,26,20,17,4,96956,33,94,32,19,55.454545
996,Faerix,5,23,50,6,5,4,180763,15,96,71,14,66.363636
997,Faerix,5,46,42,20,14,15,30108,86,96,95,11,80.000000
998,Nexoon,4,31,1,6,20,11,17851,87,94,62,13,29.090909
999,Mythron,2,40,13,20,11,10,32369,27,122,27,3,48.181818